services:
  # Servicio para python 
  python-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000" 
    # volumes:
    #   - .:/usr/src/app
    networks:
      - devops_network
    depends_on:
      - wiremock_service
    # tty: true 
  
  # Servicio para wiremock
  wiremock_service:
    build:
      context: .
      dockerfile: Dockerfile.wiremock
    ports:
      - "8080"
    # volumes:
    #   - ./test/wiremock/mappings:/home/wiremock/mappings
    command: ["--verbose"]
    networks:
      - devops_network
  
  # Servicio de Jenkins
  jenkins:
    image: jenkins/jenkins:lts-jdk17
    ports:
      - 8082:8080
      - 50000:50000
    container_name: jenkins
    # privileged: true
    volumes:
      - jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - devops_network

  # Servicio para agentes en jenkins
  agent-pipeline-jenkins-1:
    build:
      context: .
      dockerfile: Dockerfile.agent
    container_name: agent-jenkins-1-general
    # privileged: true
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock 
    expose:
      - 22
    environment:
      - JENKINS_AGENT_SSH_PUBKEY=ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCrQ1dGcVKe+jkTCfaDue0Vk3R9eoV1RYKLPvx41DsHFYtBPlgXtF8rRvxzyOneHP8J2Itrswag0tB64Njco9oYdMkrBxDpkEh52/gqoYimTZY4W4lLqbG2hYVFtD75xrcUCk/LTtoDQECT6scTRVVj5TKvTmKLtm81FjhoYtmcLtZfcyvuVae3+ZJ7j08s29qGaMwoOHrGJ7HlLgL+fWQzcS7Lok0vAAK4rQi42Y4/yRks6WvpVPUwMMnR1EkLk3REMsB//cpBj0RTR5/PYRSzi8/wKXKE4tpwhfKJ1wxmh8jD/62kWURp9t1epEGn9Q9SX6+Hn1SSROo1dZ+ndGROuJkcQw3peuYxd1NvYGTqWzyt/ZNt4mgsJMuS2sKaRkk6wqMB+BnCLWRUhZOwC99WG2A7MsHh+5F7yRNDKuEZWjtVuw/zOkyIwS6Lh/pHn8A9lMnJ3N59NRbAR5ehTC/asJbLOleiyhXRr4L9HU5vR2pGyVgBXGRqqzUde8gmgKNBbBo9/5q39gRG7ttk2zAiu8GUQgMLo6Ad4YdIqYkbhMY0jl4iabo+V0YvWBQgA8nbZjLql0OEwZtQCoOcF4x93jPRN5YxemtaxCaxuPx2hlEsoFjQuiKe/EUfYTh2DYyvdPZm0GFEGiQGGxq3IeCioqbpnafXkV2P55+vk+DrHw== kevin-orozco@TDS157
    networks:
      - devops_network

  agent-jenkins-2-test-unit:
    build:
      context: .
      dockerfile: Dockerfile.agent-unit
    container_name: agent-jenkins-2-test-unit
    # privileged: true
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock 
    expose:
      - 22
    environment:
      - JENKINS_AGENT_SSH_PUBKEY=ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCrQ1dGcVKe+jkTCfaDue0Vk3R9eoV1RYKLPvx41DsHFYtBPlgXtF8rRvxzyOneHP8J2Itrswag0tB64Njco9oYdMkrBxDpkEh52/gqoYimTZY4W4lLqbG2hYVFtD75xrcUCk/LTtoDQECT6scTRVVj5TKvTmKLtm81FjhoYtmcLtZfcyvuVae3+ZJ7j08s29qGaMwoOHrGJ7HlLgL+fWQzcS7Lok0vAAK4rQi42Y4/yRks6WvpVPUwMMnR1EkLk3REMsB//cpBj0RTR5/PYRSzi8/wKXKE4tpwhfKJ1wxmh8jD/62kWURp9t1epEGn9Q9SX6+Hn1SSROo1dZ+ndGROuJkcQw3peuYxd1NvYGTqWzyt/ZNt4mgsJMuS2sKaRkk6wqMB+BnCLWRUhZOwC99WG2A7MsHh+5F7yRNDKuEZWjtVuw/zOkyIwS6Lh/pHn8A9lMnJ3N59NRbAR5ehTC/asJbLOleiyhXRr4L9HU5vR2pGyVgBXGRqqzUde8gmgKNBbBo9/5q39gRG7ttk2zAiu8GUQgMLo6Ad4YdIqYkbhMY0jl4iabo+V0YvWBQgA8nbZjLql0OEwZtQCoOcF4x93jPRN5YxemtaxCaxuPx2hlEsoFjQuiKe/EUfYTh2DYyvdPZm0GFEGiQGGxq3IeCioqbpnafXkV2P55+vk+DrHw== kevin-orozco@TDS157
    networks:
      - devops_network

  agent-jenkins-2-test-rest:
    build:
      context: .
      dockerfile: Dockerfile.agent-rest
    container_name: agent-jenkins-2-test-rest
    # privileged: true
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock 
    expose:
      - 22
    environment:
      - JENKINS_AGENT_SSH_PUBKEY=ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCrQ1dGcVKe+jkTCfaDue0Vk3R9eoV1RYKLPvx41DsHFYtBPlgXtF8rRvxzyOneHP8J2Itrswag0tB64Njco9oYdMkrBxDpkEh52/gqoYimTZY4W4lLqbG2hYVFtD75xrcUCk/LTtoDQECT6scTRVVj5TKvTmKLtm81FjhoYtmcLtZfcyvuVae3+ZJ7j08s29qGaMwoOHrGJ7HlLgL+fWQzcS7Lok0vAAK4rQi42Y4/yRks6WvpVPUwMMnR1EkLk3REMsB//cpBj0RTR5/PYRSzi8/wKXKE4tpwhfKJ1wxmh8jD/62kWURp9t1epEGn9Q9SX6+Hn1SSROo1dZ+ndGROuJkcQw3peuYxd1NvYGTqWzyt/ZNt4mgsJMuS2sKaRkk6wqMB+BnCLWRUhZOwC99WG2A7MsHh+5F7yRNDKuEZWjtVuw/zOkyIwS6Lh/pHn8A9lMnJ3N59NRbAR5ehTC/asJbLOleiyhXRr4L9HU5vR2pGyVgBXGRqqzUde8gmgKNBbBo9/5q39gRG7ttk2zAiu8GUQgMLo6Ad4YdIqYkbhMY0jl4iabo+V0YvWBQgA8nbZjLql0OEwZtQCoOcF4x93jPRN5YxemtaxCaxuPx2hlEsoFjQuiKe/EUfYTh2DYyvdPZm0GFEGiQGGxq3IeCioqbpnafXkV2P55+vk+DrHw== kevin-orozco@TDS157
    networks:
      - devops_network

  # Nuevo servicio para JMeter
  jmeter:
    image: justb4/jmeter:5.4 
    container_name: jmeter
    volumes:
      - ./test/jmeter/test_plans:/jmeter/apache-jmeter-5.4/bin/test_plans 
      - ./test/jmeter/results:/jmeter/apache-jmeter-5.4/bin/results 
    networks:
      - devops_network
    depends_on:
      - python-app 
    command: ["-n", "-t", "/opt/jmeter/bin/test_plans/flask.jmx", "-l", "/opt/jmeter/bin/results/jmeter_results.jtl", "-e", "-o", "/opt/jmeter/bin/results/html_report"]

networks:
  devops_network:
    driver: bridge

volumes:
  jenkins_data: {}